# Build stage

FROM registry.redhat.io/ubi9/go-toolset:9.8-1791182877@sha256:d45bb2ba2e518d3edf14ad3baf6c57fdc7cc44c996cad1200f71036f7c1c8d29 AS build-env

ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1

USER root
RUN mkdir -p /opt/app-root && mkdir -p /opt/app-root/src && git config --global --add safe.directory /opt/app-root/src

WORKDIR /opt/app-root/src/
COPY . .

RUN go mod download


ARG SERVER_LDFLAGS
RUN go build -mod=readonly -trimpath -ldflags "$(SERVER_LDFLAGS)" -o backfill-redis ./cmd/backfill-index

# Install stage
FROM registry.redhat.io/rhel9/redis-6@sha256:42625debc113db4db3d246a13a19d5db00714c9eb888dd2061742507b8565068
COPY --from=build-env /opt/app-root/src/backfill-redis /usr/local/bin/backfill-redis
COPY LICENSE /licenses/license.txt
WORKDIR /opt/app-root/src/home

LABEL description="Backfillredis is a job that will go through the TLog and make sure that missing entries are added to the search index."
LABEL io.k8s.description="Backfillredis is a job that will go through the TLog and make sure that missing entries are added to the search index."
LABEL io.k8s.display-name="Backfillredis container image for Red Hat Trusted Signer"
LABEL io.openshift.tags="backfill-redis trusted-signer"
LABEL summary="Provides the backfill-redis binary for a rekor server"
LABEL com.redhat.component="backfill-redis"
LABEL name="rhtas/rekor-backfill-redis-rhel9"

USER 65532:65532

#ENTRYPOINT
ENTRYPOINT [ "backfill-redis" ]
