# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:486.0.0@sha256:4f123c1ff6fefc615a6f5b4746cbe4647b41463b5d689ce21dbcfce43ccef117
RUN apt-get install -y netcat
