# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:484.0.0@sha256:609cc2dfd7b97321ce9800e026177d0a8420638f83f02be481b19b6dd06f5fa6
RUN apt-get install -y netcat
