# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:482.0.0@sha256:535f4a8d29b135a2c1cbe920a30226d9221460a62dac3453e93828587d8fe2ac
RUN apt-get install -y netcat
