apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/build-nudge-files: controllers/constants/*
    build.appstudio.openshift.io/repo: https://github.com/securesign/rekor?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && ( "Dockerfile.rekor-server.rh".pathChanged() || ".tekton/rekor-server-push.yaml".pathChanged()
      || "trigger-konflux-builds.txt".pathChanged() || "go.mod".pathChanged() || "go.sum".pathChanged()
      || "cmd/rekor-server".pathChanged() || "pkg".pathChanged() || "Makefile".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rekor
    appstudio.openshift.io/component: rekor-server
    pipelines.appstudio.openshift.io/type: build
  name: rekor-server-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: dockerfile
    value: Dockerfile.rekor-server.rh
  - name: git-url
    value: '{{repo_url}}'
  - name: output-image
    value: quay.io/securesign/rekor-server:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: '[{"path":".","type":"gomod"},{"path":"./hack/tools","type":"gomod"}]'
  - name: go_unit_test
    value: "true"
  - name: go_base_image
    value: brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23@sha256:44fd8f88f3b6463cda15571260f9ca3a0b78d3c8c8827a338e04ab3a23581a88
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/docker-build-oci-ta.yaml
    resolver: git
  taskRunSpecs:
  - pipelineTaskName: prefetch-dependencies
    stepSpecs:
    - computeResources:
        limits:
          cpu: "3"
          memory: 3Gi
        requests:
          cpu: "3"
          memory: 3Gi
      name: prefetch-dependencies
  taskRunTemplate:
    serviceAccountName: build-pipeline-rekor-server
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
