apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/rekor?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "release-1.2"  && ( "Dockerfile.rekor-cli.rh".pathChanged() || ".tekton/rekor-cli-pull-request.yaml".pathChanged()
      || "trigger-konflux-builds.txt".pathChanged() || "go.mod".pathChanged() || "go.sum".pathChanged()
      || "cmd/rekor-cli".pathChanged() || "pkg".pathChanged() || "Makefile".pathChanged()
      || "Build.mak".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: tas-tools-v1-2
    appstudio.openshift.io/component: rekor-cli-v1-2
    pipelines.appstudio.openshift.io/type: build
  name: rekor-cli-v1-2-on-pull-request
  namespace: rhtas-tenant
spec:
  params:
  - name: release-version
    value: "1.2.2"
  - name: dockerfile
    value: Dockerfile.rekor-cli.rh
  - name: git-url
    value: '{{repo_url}}'
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/securesign/rekor-cli:on-pr-{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: prefetch-input
    value: '[{"type": "gomod", "path": "."}, {"type": "gomod", "path": "hack/tools"}]'
  - name: hermetic
    value: "true"
  - name: build-source-image
    value: "true"
  - name: go_unit_test
    value: "true"
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/docker-build-oci-ta.yaml
    resolver: git
  taskRunSpecs:
  - pipelineTaskName: prefetch-dependencies
    stepSpecs:
    - computeResources:
        limits:
          cpu: "3"
          memory: 3Gi
        requests:
          cpu: "3"
          memory: 3Gi
      name: prefetch-dependencies
  taskRunTemplate:
    serviceAccountName: build-pipeline-rekor-cli-v1-2
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
